<template>
  <div class="item">
    <span class="item__title">
      {{ props.element.title }}
    </span>
    <div class="item__arrow left-arrow" @click="decreaseValue">
      <font-awesome-icon icon="caret-up" />
    </div>
    <div class="item__number" :class="{ shake }" @:animationend="shake = false">
      {{ props.element.number }}
    </div>
    <div class="item__arrow right-arrow" @click="increaseValue">
      <font-awesome-icon icon="caret-down" />
    </div>
  </div>
</template>

<script lang="ts" setup>
import { ref, toRef, computed } from 'vue'

// eslint-disable-next-line no-undef
const props = defineProps<{
  element: {
    number: object
  },
}>()

const shake = ref(false)

// const title = toRef(props, 'title', 'Year')
// const number = toRef(props, 'number', 0)

function daysInThisMonth () {
  const now = new Date()
  return new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate()
}

</script>

<style lang="scss" scoped>
@import url('https://fonts.googleapis.com/css?family=Poppins&display=swap');

.item {
  width: 70px;
  display: flex;
  flex-direction: column;

  &__title {
     color: #fff;
   }

  &__arrow {
    color: #d8cdf6;
    font-size: 35px;
    font-weight: bold;
    cursor: pointer;
    transition: color .25s linear;

    &:hover {
      color: #7a6ba3;
    }
  }

  &__number {
    width: 100%;
    height: 80px;
    font-family: 'Poppins', sans-serif;
    font-size: 30px;
    background-color: #8157f4;
    border-radius: 1rem;
    text-align: center;
    line-height: 80px;
    color: #fff;
    -webkit-box-shadow: 0px 13px 74px -15px rgba(129,87,244,1);
    -moz-box-shadow: 0px 13px 74px -15px rgba(129,87,244,1);
    box-shadow: 0px 13px 74px -15px rgba(129,87,244,1);
  }
}

.shake {
  -webkit-animation: shake 0.8s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
  animation: shake 0.8s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2019-7-14 11:8:54
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation shake-horizontal
 * ----------------------------------------
 */
@-webkit-keyframes shake {
  0%,
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
  }
  10%,
  30%,
  50%,
  70% {
    -webkit-transform: translateX(-10px);
    transform: translateX(-10px);
  }
  20%,
  40%,
  60% {
    -webkit-transform: translateX(10px);
    transform: translateX(10px);
  }
  80% {
    -webkit-transform: translateX(8px);
    transform: translateX(8px);
  }
  90% {
    -webkit-transform: translateX(-8px);
    transform: translateX(-8px);
  }
}
@keyframes shake {
  0%,
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
  }
  10%,
  30%,
  50%,
  70% {
    -webkit-transform: translateX(-10px);
    transform: translateX(-10px);
  }
  20%,
  40%,
  60% {
    -webkit-transform: translateX(10px);
    transform: translateX(10px);
  }
  80% {
    -webkit-transform: translateX(8px);
    transform: translateX(8px);
  }
  90% {
    -webkit-transform: translateX(-8px);
    transform: translateX(-8px);
  }
}
</style>
